<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Support\Facades\DB;

use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arrPermiss = [
            "master"=>
            [
                "ler" => [
                      "painel" => "s",
                      "cad-conteudo" => "s",
                      "posts" => "s",
                      "pages" => "s",
                      "documents" => "s",
                      "leis" => "s",
                      "concursos" => "s",
                      "decretos" => "s",
                      "diarios" => "s",
                      "portarias" => "s",
                      "convenios" => "s",
                      "box-archives" => "s",
                      "archives" => "s",
                      "archives_category" => "s",
                      "admin.sic" => "s",
                      "sic" => "s",
                      "licitacoes" => "s",
                      "biddings" => "s",
                      "biddings_categories" => "s",
                      "biddings_phases" => "s",
                      "biddings_genres" => "s",
                      "biddings_types" => "s",
                      "financeiro" => "s",
                      "extrato" => "s",
                      "receitas" => "s",
                      "despesas" => "s",
                      "config" => "s",
                      "documentos" => "s",
                      "sistema" => "s",
                      "users" => "s",
                      "fornecedores" => "s",
                      "cat_receitas" => "s",
                      "cat_despesas" => "s",
                      "f_pagamento" => "s",
                      "contas" => "s",
                      "permissions" => "s",
                      "tags" => "s",
                      "qoptions" => "s",
                      "enterprise" => "s"
                   ],
                "create" => [
                         "posts" => "s",
                         "pages" => "s",
                         "leis" => "s",
                         "concursos" => "s",
                         "decretos" => "s",
                         "diarios" => "s",
                         "portarias" => "s",
                         "convenios" => "s",
                         "archives" => "s",
                         "archives_category" => "s",
                         "sic" => "s",
                         "biddings" => "s",
                         "biddings_categories" => "s",
                         "biddings_phases" => "s",
                         "biddings_genres" => "s",
                         "biddings_types" => "s",
                         "extrato" => "s",
                         "receitas" => "s",
                         "despesas" => "s",
                         "documentos" => "s",
                         "sistema" => "s",
                         "users" => "s",
                         "fornecedores" => "s",
                         "cat_receitas" => "s",
                         "cat_despesas" => "s",
                         "f_pagamento" => "s",
                         "contas" => "s",
                         "permissions" => "s",
                         "tags" => "s",
                         "qoptions" => "s",
                         "enterprise" => "s"
                      ],
                "update" => [
                            "posts" => "s",
                            "pages" => "s",
                            "leis" => "s",
                            "concursos" => "s",
                            "decretos" => "s",
                            "diarios" => "s",
                            "portarias" => "s",
                            "convenios" => "s",
                            "archives" => "s",
                            "archives_category" => "s",
                            "sic" => "s",
                            "biddings" => "s",
                            "biddings_categories" => "s",
                            "biddings_phases" => "s",
                            "biddings_genres" => "s",
                            "biddings_types" => "s",
                            "extrato" => "s",
                            "receitas" => "s",
                            "despesas" => "s",
                            "documentos" => "s",
                            "sistema" => "s",
                            "users" => "s",
                            "fornecedores" => "s",
                            "cat_receitas" => "s",
                            "cat_despesas" => "s",
                            "f_pagamento" => "s",
                            "contas" => "s",
                            "permissions" => "s",
                            "tags" => "s",
                            "qoptions" => "s",
                            "enterprise" => "s"
                         ],
                "delete" => [
                               "posts" => "s",
                               "pages" => "s",
                               "leis" => "s",
                               "concursos" => "s",
                               "decretos" => "s",
                               "diarios" => "s",
                               "portarias" => "s",
                               "convenios" => "s",
                               "archives" => "s",
                               "archives_category" => "s",
                               "sic" => "s",
                               "biddings" => "s",
                               "biddings_categories" => "s",
                               "biddings_phases" => "s",
                               "biddings_genres" => "s",
                               "biddings_types" => "s",
                               "extrato" => "s",
                               "receitas" => "s",
                               "despesas" => "s",
                               "documentos" => "s",
                               "sistema" => "s",
                               "users" => "s",
                               "fornecedores" => "s",
                               "cat_receitas" => "s",
                               "cat_despesas" => "s",
                               "f_pagamento" => "s",
                               "contas" => "s",
                               "permissions" => "s",
                               "tags" => "s",
                               "qoptions" => "s",
                               "enterprise" => "s"
                            ],
                "ler_arquivos" => [
                                  "posts" => "s",
                                  "pages" => "s",
                                  "leis" => "s",
                                  "concursos" => "s",
                                  "decretos" => "s",
                                  "diarios" => "s",
                                  "portarias" => "s",
                                  "convenios" => "s",
                                  "archives" => "s",
                                  "archives_category" => "s",
                                  "sic" => "s",
                                  "biddings" => "s",
                                  "biddings_categories" => "s",
                                  "biddings_phases" => "s",
                                  "biddings_genres" => "s",
                                  "biddings_types" => "s",
                                  "extrato" => "s",
                                  "receitas" => "s",
                                  "despesas" => "s",
                                  "documentos" => "s",
                                  "sistema" => "s",
                                  "users" => "s",
                                  "fornecedores" => "s",
                                  "cat_receitas" => "s",
                                  "cat_despesas" => "s",
                                  "f_pagamento" => "s",
                                  "contas" => "s",
                                  "permissions" => "s",
                                  "tags" => "s",
                                  "qoptions" => "s",
                                  "enterprise" => "s"
                               ]
            ],
            "admin"=>
            [
                "ler" => [
                      "painel" => "s",
                      "cad-conteudo" => "s",
                      "posts" => "s",
                      "pages" => "s",
                      "documents" => "s",
                      "leis" => "s",
                      "concursos" => "s",
                      "decretos" => "s",
                      "diarios" => "s",
                      "portarias" => "s",
                      "convenios" => "s",
                      "admin.sic" => "s",
                      "sic" => "s",
                      "licitacoes" => "s",
                      "biddings" => "s",
                      "biddings_categories" => "s",
                      "biddings_phases" => "s",
                      "biddings_genres" => "s",
                      "biddings_types" => "s",
                      "config" => "s",
                      "sistema" => "s",
                      "users" => "s"
                   ],
                "create" => [
                         "posts" => "s",
                         "pages" => "s",
                         "leis" => "s",
                         "concursos" => "s",
                         "decretos" => "s",
                         "diarios" => "s",
                         "portarias" => "s",
                         "convenios" => "s",
                         "sic" => "s",
                         "biddings" => "s",
                         "biddings_categories" => "s",
                         "biddings_phases" => "s",
                         "biddings_genres" => "s",
                         "biddings_types" => "s",
                         "documentos" => "s",
                         "sistema" => "s",
                         "users" => "s",
                         "permissions" => "s",
                         "tags" => "s",
                         "qoptions" => "s"
                      ],
                "update" => [
                            "posts" => "s",
                            "pages" => "s",
                            "leis" => "s",
                            "concursos" => "s",
                            "decretos" => "s",
                            "diarios" => "s",
                            "portarias" => "s",
                            "convenios" => "s",
                            "sic" => "s",
                            "biddings" => "s",
                            "biddings_categories" => "s",
                            "biddings_phases" => "s",
                            "biddings_genres" => "s",
                            "biddings_types" => "s",
                            "documentos" => "s",
                            "sistema" => "s",
                            "users" => "s",
                            "permissions" => "s",
                            "tags" => "s",
                            "qoptions" => "s"
                         ],
                "delete" => [
                               "posts" => "s",
                               "pages" => "s",
                               "leis" => "s",
                               "concursos" => "s",
                               "decretos" => "s",
                               "diarios" => "s",
                               "portarias" => "s",
                               "convenios" => "s",
                               "sic" => "s",
                               "biddings" => "s",
                               "biddings_categories" => "s",
                               "biddings_phases" => "s",
                               "biddings_genres" => "s",
                               "biddings_types" => "s",
                               "documentos" => "s",
                               "sistema" => "s",
                               "users" => "s",
                               "permissions" => "s",
                               "tags" => "s",
                               "qoptions" => "s"
                            ],
                "ler_arquivos" => [
                                  "posts" => "s",
                                  "pages" => "s",
                                  "leis" => "s",
                                  "concursos" => "s",
                                  "decretos" => "s",
                                  "diarios" => "s",
                                  "portarias" => "s",
                                  "convenios" => "s",
                                  "sic" => "s",
                                  "biddings" => "s",
                                  "biddings_categories" => "s",
                                  "biddings_phases" => "s",
                                  "biddings_genres" => "s",
                                  "biddings_types" => "s",
                                  "documentos" => "s",
                                  "sistema" => "s",
                                  "users" => "s",
                                  "permissions" => "s",
                                  "tags" => "s",
                                  "qoptions" => "s"
                               ]
             ],
        ];
        Permission::truncate();
        DB::table('permissions')->insert([
            [
                'name'=>'Master',
                'redirect_login'=>'/admin/home',
                'description'=>'Desenvolvedores',
                'active'=>'s',
                'id_menu'=>json_encode($arrPermiss['master']),
            ],
            [
                'name'=>'Adminstrador',
                'redirect_login'=>'/admin/home',
                'description'=>'Adiminstradores do sistema',
                'active'=>'s',
                'id_menu'=>json_encode($arrPermiss['admin']),
            ],
            [
                'name'=>'Gerente',
                'redirect_login'=>'/admin/home',
                'description'=>'Gerente do sistema menos que administrador secundário',
                'active'=>'s',
                'id_menu'=>json_encode([]),
            ],
            [
                'name'=>'Escritório1',
                'redirect_login'=>'/admin/home',
                'description'=>'Pessoas do escritório',
                'active'=>'s',
                'id_menu'=>json_encode([]),
            ],
            [
                'name'=>'Escritório2',
                'redirect_login'=>'/admin/home',
                'description'=>'Pessoas do escritório',
                'active'=>'s',
                'id_menu'=>json_encode([]),
            ],
            [
                'name'=>'Servidores',
                'redirect_login'=>'/admin/home',
                'description'=>'Servidores publicos',
                'active'=>'s',
                'id_menu'=>json_encode([]),
            ],
            [
                'name'=>'Fornecedores',
                'redirect_login'=>'/admin/home',
                'description'=>'Fornecedores de serviços',
                'active'=>'s',
                'id_menu'=>json_encode([]),
            ],
            [
                'name'=>'Internautas',
                'redirect_login'=>'/internautas',
                'description'=>'Somente Internautas, Sem privilêgios de administração acesso a área restrita do site','active'=>'s',
                'id_menu'=>json_encode([]),
            ],
        ]);
    }
}
